[_]
schema-version = "0.2"

[[build.env]]
name = "BP_ENABLE_RUNTIME"
value = "true"

[[build.env]]
name = "BP_CPYTHON_VERSION"
value = "3.11.9"

[[build.env]]
name = "PIP_INDEX_URL"
value = "https://pypi.org/simple"

[[buildpacks]]
id = "heroku/python"
version = "0.10.2"

[[buildpacks]]
id = "heroku/procfile"
version = "3.0.1"
